spring:
  profiles: node1
  application:
    name: registry-node-1
server:
  port: 8761
eureka:
  instance:
    hostname: node1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://node2:8769/eureka/