spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  application:
    name: config-server
  cloud:
    bus:
      trace:
        enabled: true
    config:
      label: master
      server:
        git:
          uri: https://github.com/kan01234/spring-cloud-learning/
          searchPaths: cloud-config
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8889/eureka/
